image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.3"
  ANDROID_SDK_TOOLS: "26.1.1"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
  - unzip android-sdk.zip -d android-sdk-linux > /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" > /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" > /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "extras;android;m2repository" > /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "extras;google;google_play_services" > /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "extras;google;m2repository" > /dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./gradlew test

#functionalTests:
#  stage: test
#  script:
#    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
#    - chmod +x android-wait-for-emulator
#    - echo y | android-sdk-linux/tools/bin/sdkmanager "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86"
#    - echo no | android-sdk-linux/tools/bin/avdmanager create avd -n Test -k "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86"
#    - android-sdk-linux/emulator64-x86 -avd test -no-window -no-audio &
#    - ./android-wait-for-emulator
#    - adb shell input keyevent 82
#    - ./gradlew cAT
